fragment BlogParts on Blog {
  __typename
  title
  meta_title
  description
  date
  image
  author
  categories {
    __typename
    category
  }
  tags {
    __typename
    tag
  }
  draft
  body
}

fragment AuthorsParts on Authors {
  __typename
  title
  description
  image
  draft
}

fragment PagesParts on Pages {
  __typename
  title
  meta_title
  description
  image
  draft
  body
}

fragment ProgramsParts on Programs {
  __typename
  title
  subtitle
  description
  phases {
    __typename
    title
    duration
    link
    content
  }
  components {
    __typename
    title
    content
    list
  }
}
