import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Determine the paths based on setup mode (theme vs project)
 * @returns {Object} Configuration object with paths and mode info
 */
function determinePaths() {
  const tokensPath = path.join(__dirname, "../tokens/tokens.json");
  const outputPath = path.join(__dirname, "../src/styles/generated-theme.css");

  if (!fs.existsSync(tokensPath)) {
    throw new Error(`Could not find tokens.json at: ${tokensPath}`);
  }

  return { tokensPath, outputPath };
}

const { tokensPath, outputPath } = determinePaths();

// Helper to convert color name from snake_case to kebab-case
const toKebab = (str) => str.replace(/_/g, "-");

// Helper to extract a clean font name
const findFont = (fontStr) =>
  fontStr.replace(/\+/g, " ").replace(/:[^:]+/g, "");

/**
 * Add color entries to CSS array from Style Dictionary format
 * @param {Array} cssLines - Array of CSS lines to append to
 * @param {Object} colors - Color object to process
 * @param {string} prefix - Optional prefix for color variable names
 */
function addColorsToCss(cssLines, colors, prefix = "") {
  Object.entries(colors).forEach(([key, colorData]) => {
    // Some keys might contain a 'value' directly, some might be nested (like primary.base)
    // We only process flat keys for now based on the old themeGenerator mapping
    // But Astroplate expects e.g. --color-primary, --color-secondary

    // In our tokens, primary is an object with 'value', 'type'
    if (colorData && typeof colorData === 'object' && colorData.value) {
      const colorName = prefix
        ? `--color-${prefix}-${toKebab(key)}`
        : `--color-${toKebab(key)}`;
      cssLines.push(`  ${colorName}: ${colorData.value};`);
    } else if (colorData && typeof colorData === 'object') {
      // Handle nested groups if necessary, or map specific ones Astroplate needs
      // Astroplate expects: primary, secondary, body, border, light, dark, text, text_dark, text_light, success, warning, danger, info

      // Let's assume Astroplate only needs the top level or specific sub-objects that have 'value'
      // For our tokens structure, `colorData` might be e.g. { primary: { base: { value: ... } } }
      // BUT we updated tokens to match theme.json structure for Astroplate: 
      // color.theme_color, color.text_color, color.accent

      // Actuallly we placed it inside color.{primary, secondary, background...} earlier.
      // Wait, looking at the previous step we added darkmode next to theme_color.
      // Let's just traverse exactly like we did before but handle the `.value`

      Object.entries(colorData).forEach(([subKey, subData]) => {
        if (subData && subData.value) {
          // we probably don't want long names like --color-theme-color-primary
          // let's just map the keys directly if they are the exact ones Astroplate needs
          const colorName = prefix
            ? `--color-${prefix}-${toKebab(subKey)}`
            : `--color-${toKebab(subKey)}`;
          cssLines.push(`  ${colorName}: ${subData.value};`);
        }
      });
    }
  });
}

/**
 * Generate theme CSS from tokens.json configuration
 * @throws {Error} If tokens.json is missing or invalid
 */
function generateThemeCSS() {
  if (!fs.existsSync(tokensPath)) {
    throw new Error(`Tokens configuration not found: ${tokensPath}`);
  }

  try {
    const tokensConfig = JSON.parse(fs.readFileSync(tokensPath, "utf8"));

    if (!tokensConfig.color || !tokensConfig.font) {
      throw new Error(
        "Invalid tokens.json: missing 'color' or 'font' section",
      );
    }

    const cssLines = [
      "/**",
      ' * Auto-generated from "tokens/tokens.json"',
      " * DO NOT EDIT THIS FILE MANUALLY",
      " * Run: node scripts/themeGenerator.js",
      " */",
      "",
      "@theme {",
      "  /* === Colors === */",
    ];

    // Astroplate expects flat variables like --color-primary, --color-body
    // In tokens.json (original), it's `color.primary.base.value` etc.
    // However, if we look at what Astroplate expects from theme.json:
    // colors.default.theme_color => primary, secondary, body, border, light, dark
    // colors.default.text_color => text, text_dark, text_light
    // colors.default.accent => success, warning, danger, info

    // Instead of mapping complex nesting, we can manually map our tokens layout since Astroplate expects specific variables.
    const mapColor = (varName, valuePath) => {
      if (valuePath) {
        cssLines.push(`  ${varName}: ${valuePath};`);
      }
    };

    // Default colors mapped from tokens.json
    mapColor("--color-primary", tokensConfig.color.primary?.base?.value);
    mapColor("--color-secondary", tokensConfig.color.secondary?.base?.value);
    mapColor("--color-body", tokensConfig.color.background?.base?.value);
    mapColor("--color-border", tokensConfig.color.border?.base?.value);
    mapColor("--color-light", tokensConfig.color.background?.light?.value);
    mapColor("--color-dark", tokensConfig.color.primary?.dark?.value || "#040404"); // Defaulting if not strictly defined

    mapColor("--color-text", tokensConfig.color.text?.secondary?.value);
    mapColor("--color-text-dark", tokensConfig.color.text?.primary?.value);
    mapColor("--color-text-light", tokensConfig.color.text?.light?.value);

    cssLines.push("", "  /* === Accent Colors === */");
    mapColor("--color-success", tokensConfig.color.accent?.success?.value);
    mapColor("--color-warning", tokensConfig.color.accent?.warning?.value);
    mapColor("--color-danger", tokensConfig.color.accent?.danger?.value);
    mapColor("--color-info", tokensConfig.color.accent?.info?.value);

    // Add darkmode colors (what we just added to tokens.json under `color.darkmode.theme_color`)
    if (tokensConfig.color.darkmode) {
      cssLines.push("", "  /* === Darkmode Colors === */");

      const dmTheme = tokensConfig.color.darkmode.theme_color || {};
      const dmText = tokensConfig.color.darkmode.text_color || {};

      mapColor("--color-darkmode-primary", dmTheme.primary?.value);
      mapColor("--color-darkmode-secondary", dmTheme.secondary?.value);
      mapColor("--color-darkmode-body", dmTheme.body?.value);
      mapColor("--color-darkmode-border", dmTheme.border?.value);
      mapColor("--color-darkmode-light", dmTheme.light?.value);
      mapColor("--color-darkmode-dark", dmTheme.dark?.value);

      mapColor("--color-darkmode-text", dmText.text?.value);
      mapColor("--color-darkmode-text-dark", dmText.text_dark?.value);
      mapColor("--color-darkmode-text-light", dmText.text_light?.value);
    }

    // Add font families
    cssLines.push("", "  /* === Font Families === */");
    const pf = tokensConfig.font?.family?.primary?.value;
    const sf = tokensConfig.font?.family?.secondary?.value;
    if (pf) cssLines.push(`  --font-primary: ${findFont(pf)}, sans-serif;`);
    if (sf) cssLines.push(`  --font-secondary: ${findFont(sf)}, sans-serif;`);

    // Add font sizes - Astroplate calculates these iteratively from base size and scale.
    // Our 'tokens.json' has them explicitly under `font.size`.
    cssLines.push("", "  /* === Font Sizes === */");

    // Convert 'rem' strings into pixel approximations if needed for text-base-sm, 
    // or just calculate based on the explicit tokens.
    // In original Astroplate theme.json: base = 16px, scale = 1.25. Let's calculate similarly or extract.
    // Astroplate expects --text-base (px), --text-base-sm (px), --text-h1..h6 (rem), --text-h1-sm..h6-sm (rem)

    // We'll mimic the old logic assuming base=16px scale=1.2 for the hX tags as that is hardcoded in Astroplate layouts logic.
    const baseSize = 16;
    const scale = 1.2;

    cssLines.push(`  --text-base: ${baseSize}px;`);
    cssLines.push(`  --text-base-sm: ${baseSize * 0.8}px;`);

    let currentSize = scale;
    for (let i = 6; i >= 1; i--) {
      cssLines.push(`  --text-h${i}: ${currentSize}rem;`);
      cssLines.push(`  --text-h${i}-sm: ${currentSize * 0.9}rem;`);
      currentSize *= scale;
    }

    cssLines.push("}");

    // Ensure output directory exists
    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write the file
    fs.writeFileSync(outputPath, cssLines.join("\n") + "\n");
    console.log("✅ Theme CSS generated successfully from tokens.json at:", outputPath);
  } catch (error) {
    throw new Error(`Failed to generate theme CSS: ${error.message}`);
  }
}

// Generate CSS on startup
try {
  generateThemeCSS();
} catch (error) {
  console.error("❌ Error:", error.message);
  process.exit(1);
}

// Check for --watch flag
if (process.argv.includes("--watch")) {
  let debounceTimer;

  const watcher = fs.watch(tokensPath, (eventType) => {
    if (eventType === "change") {
      // Debounce to avoid multiple triggers
      clearTimeout(debounceTimer);
      debounceTimer = setTimeout(() => {
        try {
          generateThemeCSS();
        } catch (error) {
          console.error("❌ Error regenerating theme CSS:", error.message);
        }
      }, 300);
    }
  });

  // Handle graceful shutdown
  process.on("SIGINT", () => {
    clearTimeout(debounceTimer);
    watcher.close();
    console.log("\n👋 Watcher stopped");
    process.exit(0);
  });

  console.log("👁️  Watching for changes to:", tokensPath);
}
